### ISSUE TITLE
Can't create CalendarView in own Project

### ISSUE THREAD

**Issue by Tobi2707** [dlemmermann/CalendarFX#16]
Hallo,
I want to create my own project and embedd your calendar view. 
Therefore I created a Sample App. It's the same code than your "CalendarApp.java".

I had to include the fontawesome .jars and your calendarfx .jars so I get no error but when running i get following error:

**`Caused by: java.lang.VerifyError: class impl.com.calendarfx.view.CalendarViewSkin$CustomMasterDetailPane overrides final method resetDividerPosition.()V**
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.calendarfx.view.CalendarView.createDefaultSkin(CalendarView.java:140)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.preferredSize(Scene.java:1643)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:846)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at sample.Main.start(Main.java:65)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	... 1 more
Exception running application sample.Main`

How can I solve this problem. I'm using Java 8.

**Comment by jotomo** [comment]
CalendarFX used a class that's now moved to ControlsFX (see https://github.com/dlemmermann/CalendarFX/commit/6dcdc60e308e3de57a6c005b6ddcc5ea7e03a18d).
Make sure to include ControlsFX >=8.40.13 in your project, which will resolve the error you're seeing (or let a build tool handle that for you).

**Comment by dlemmermann** [comment]
I am assuming you are using the latest release of ControlsFX but not of CalendarFX. Please use the release on GitHub. Version 8.4.1.

**Comment by dlemmermann** [comment]
I needed a new method on MasterDetailPane (resetDividerPosition()) for CalendarFX but couldn't wait for the next ControlsFX release, so I added a CustomMasterDetailPane inside the CalendarViewSkin class. Later on the method could also be found on MasterDetailPane inside ControlsFX, which is when I removed the custom class for 8.4.1.

**Comment by Tobi2707** [comment]
Ah I just got i solved by using an older controlsFx lib. Did not load the newest CalendarFx. This should solve the problem. But it's awesome how fast I got an answer at what you've created with CalendarFX. Thumbs up!

**Comment by dlemmermann** [comment]
OK, but now you are using two old versions :-)

**Comment by Tobi2707** [comment]
Yes but can't finde the newest calendarfx 8.4.1 .jars only got 8.4.0 :P

**Comment by dlemmermann** [comment]
If you run the "install" target on the parent project then you will end up finding all the required (third party) JARs inside the "assembly" module inside the "target/bin/ext" folder.

**Comment by dlemmermann** [comment]
If you checkout this project and build it you will have 8.4.1.

**Comment by dlemmermann** [comment]
I really need to get this project into a central maven repository. Working on that.

**Comment by Tobi2707** [comment]
What do you mean with run the "install" target? I have now downloaded the CalendarFX-master folder.

**Comment by dlemmermann** [comment]
I mean that you should checkout the project from GitHub and execute the maven "install" target. Are you familiar with git repositories and maven?

**Comment by Tobi2707** [comment]
Oh sorry, never used Github before. With my new project i want to start version control via Git, but before I've just downloaded the Zip File...Is it difficult or is there another way?

Another question: The test app tells that this is only a trial version and I need a license in 90 days, is it still needed? Because on your homepage I did not find prices or something like that.

**Comment by dlemmermann** [comment]
CalendarFX used to be a commercial product but now it is open source. So you no longer need a license and there is no money to be paid.

Have you used Maven before?

**Comment by Tobi2707** [comment]
Ah okay nice to know.

Not really, sometimes I "use" maven while importing new projects into my IntelliJ IDEA. But if it'S to complicated to explain I can hopefully use the older version of CalendarFX

**Comment by dlemmermann** [comment]
OK, for now just use the older version and try to get used to GIT and Maven. Then you can checkout this project from GitHub and work with the last release.

**Comment by Tobi2707** [comment]
Okay thank you for your help! Really good job!
