### ISSUE TITLE
Space in MonthViewSkin is shown with a time and causes NPEs

### ISSUE THREAD

**Issue by baumeister** [dlemmermann/CalendarFX#206]
When using the MonthView will full day event, fake helper entries are create to occupy space.
These entries will display with a time in the view:

![image](https://github.com/dlsc-software-consulting-gmbh/CalendarFX/assets/2120116/6b2e5115-9315-45ad-9c7d-bc10c30119ce)

See the 12:00 entries in the above image

These space entries are clickable and if done so, will cause an NPE because they don't belong to a calendar:

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "com.calendarfx.model.Calendar.readOnlyProperty()" because the return value of "com.calendarfx.model.Entry.getCalendar()" is null
	at com.calendarfx.view.popover.EntryDetailsView.<init>(EntryDetailsView.java:102)
	at com.calendarfx.view.popover.EntryPopOverContentPane.<init>(EntryPopOverContentPane.java:60)

However this issue can easily be resolved by setting them also to fullday:

So add the setFullDay line MonthViewSkin:update

```
                                          /*
            				 * Do not use factory for this. SPACE is important to guarantee that the blank
            				 * entries have the same height as the regular entries.
            				 */
            				MonthEntryView label = new MonthEntryView(new Entry<>(SPACE));
            				label.setVisible(false);
            				label.getEntry().setFullDay(true);
            				label.getProperties().put("control", getSkinnable());
            				fullDayNodes[i] = label;

```

Now the space item correctly shows as white space without a time, and is not clickable and does not cause NPEs.

**Comment by baumeister** [comment]
For a test case, the same code can be used as mentioned here:

https://github.com/dlsc-software-consulting-gmbh/CalendarFX/issues/193#issuecomment-1753922921
