### ISSUE TITLE
 MonthView Entry Modification Pop-up Closes Prematurely During Date or Time Change

### ISSUE THREAD

**Issue by leewyatt** [dlemmermann/CalendarFX#208]
We're encountering a problematic behavior in the MonthView component, where attempting to modify the time or date of an entry results in the modification pop-up closing automatically before the input is fully completed. For instance, if one intends to change the time to 12 o'clock and starts by entering "1," the pop-up closes immediately, preventing any further input. This issue makes it impossible to complete the modification of an entry's time or date within the interface. 

<img width="600" alt="image" src="https://github.com/dlsc-software-consulting-gmbh/CalendarFX/assets/75261429/b624ebb3-0a47-480e-ab68-092f53c33a98">

**Comment by MattTheCuber** [comment]
I am also experiencing this issue.

**Comment by MattTheCuber** [comment]
Looks like when you change an entry, the scene rebuilds and the pop over loses its anchor.

```java
popOver.addEventFilter(WindowEvent.WINDOW_HIDDEN, evt -> {
    Thread.dumpStack();
});
```

```
java.lang.Exception: Stack trace
        at java.base/java.lang.Thread.dumpStack(Thread.java:1991)
        at com.my.App.lambda$customizeCalendarView$10(App.java:247)
        at javafx.base@21/com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:321)
        at javafx.base@21/com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
        at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:219)
        at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:178)
        at javafx.base@21/com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
        at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
        at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base@21/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at javafx.base@21/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.base@21/javafx.event.Event.fireEvent(Event.java:198)
        at javafx.graphics@21/javafx.stage.Window.fireEvent(Window.java:1391)
        at javafx.graphics@21/javafx.stage.Window$12.invalidated(Window.java:1192)
        at javafx.base@21/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
        at javafx.base@21/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
        at javafx.graphics@21/javafx.stage.Window.setShowing(Window.java:1239)
        at javafx.graphics@21/javafx.stage.Window.hide(Window.java:1264)
        at javafx.graphics@21/javafx.stage.PopupWindow.hide(PopupWindow.java:492)
        at org.controlsfx.control.PopOver.hide(PopOver.java:533)
        at org.controlsfx.control.PopOver.hide(PopOver.java:498)
        at javafx.graphics@21/javafx.stage.PopupWindow.lambda$new$0(PopupWindow.java:148)
        at javafx.base@21/javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:86)
        at javafx.base@21/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:192)
        at javafx.base@21/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
        at javafx.base@21/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:78)
        at javafx.graphics@21/com.sun.javafx.scene.TreeShowingProperty.invalidate(TreeShowingProperty.java:92)
        at javafx.graphics@21/com.sun.javafx.scene.TreeShowingProperty.updateTreeShowing(TreeShowingProperty.java:136)
        at javafx.graphics@21/com.sun.javafx.scene.TreeShowingProperty.windowChanged(TreeShowingProperty.java:128)
        at javafx.graphics@21/com.sun.javafx.scene.TreeShowingProperty.sceneChanged(TreeShowingProperty.java:114)
        at javafx.graphics@21/com.sun.javafx.scene.TreeShowingProperty.lambda$new$2(TreeShowingProperty.java:45)
        at javafx.base@21/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:192)
        at javafx.base@21/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
        at javafx.base@21/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:80)
        at javafx.base@21/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
        at javafx.graphics@21/javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1044)
        at javafx.graphics@21/javafx.scene.Node.invalidatedScenes(Node.java:1095)
        at javafx.graphics@21/javafx.scene.Node.setScenes(Node.java:1133)
        at javafx.graphics@21/javafx.scene.Parent$3.onProposedChange(Parent.java:606)
        at javafx.base@21/com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
        at impl.com.calendarfx.view.util.Util.removeChildren(Util.java:80)
        at impl.com.calendarfx.view.MonthViewSkin$MonthDayEntriesPane.update(MonthViewSkin.java:662)
        at impl.com.calendarfx.view.MonthViewSkin$MonthDayEntriesPane.lambda$new$0(MonthViewSkin.java:632)
        at javafx.graphics@21/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:138)
        at javafx.graphics@21/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at javafx.graphics@21/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at javafx.graphics@21/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics@21/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
        at java.base/java.lang.Thread.run(Thread.java:1447)
```

**Comment by MattTheCuber** [comment]
Found a workaround that works pretty well. Glitches a little bit when typing, but overall much better than constantly closing.

```java
calendarView.setEntryDetailsPopOverContentCallback(param -> {
    EntryPopOverContentPane popUp = new EntryPopOverContentPane(
            param.getPopOver(),
            param.getDateControl(),
            param.getEntry());

    PopOver popOver = popUp.getPopOver();
    popOver.addEventFilter(WindowEvent.WINDOW_HIDDEN, evt -> {
        boolean anchorLost = (popOver.getOwnerNode() == null) || (popOver.getOwnerNode().getScene() == null);
        if (anchorLost) {
            Platform.runLater(() -> {
                EntryViewBase<?> entryView = calendarView.findEntryView(param.getEntry());
                if (entryView != null && entryView.getScene() != null) {
                    popOver.show(entryView);
                }
            });
        }
    });

    return popUp;
});
```
