### ISSUE TITLE
JavaFX app build failed due to invalid module when CalendarFX added to gradle build file

### ISSUE THREAD

**Issue by infinite-dev22** [dlemmermann/CalendarFX#209]
I want to use CalendarFX `11.12.6` in my project but whenever I add the dependancy (
    `implementation 'com.calendarfx:view:11.12.6'`) to my project I get the error below when I run the project.

Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for /home/inifinite/.m2/repository/org/jooq/jool-java-8/0.9.14/jool-java-8-0.9.14.jar
Caused by: java.lang.IllegalArgumentException: jool.java.8: Invalid module name: '8' is not a Java identifier.
Is there anything I am doing wrong or missing out on.
Thanks.

**Comment by dlemmermann** [comment]
I do not know why this dependency exists. You should search the dependency tree and try to find out. And then maybe add it to an "exclusions" list in your pom file. For each dependency you can list pulled in dependencies that you do not want.

Something like this:

<img width="717" alt="Bildschirmfoto 2024-03-24 um 13 55 39" src="https://github.com/dlsc-software-consulting-gmbh/CalendarFX/assets/9534301/c84bf9ce-ac79-424e-bf5b-fad6ab647f14">

**Comment by surafelwondimagegn** [comment]
Can you specify the error ,mostly gradle error come up with gradle setup if
you start with online gradle you should need online ….

**Comment by infinite-dev22** [comment]
Thank you @dlemmermann, I do exclude the failing dependency and I now get a different Error shown below:
`
Exception in thread "JavaFX Application Thread" java.util.ServiceConfigurationError: java.time.zone.ZoneRulesProvider: Provider net.fortuna.ical4j.model.DefaultZoneRulesProvider could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at java.base/java.time.zone.ZoneRulesProvider.<clinit>(ZoneRulesProvider.java:177)
	at java.base/java.time.ZoneRegion.ofId(ZoneRegion.java:121)
	at java.base/java.time.ZoneId.of(ZoneId.java:411)
	at java.base/java.time.ZoneId.of(ZoneId.java:359)
	at java.base/java.time.ZoneId.of(ZoneId.java:315)
	at java.base/java.util.TimeZone.toZoneId0(TimeZone.java:605)
	at java.base/java.util.TimeZone.toZoneId(TimeZone.java:582)
	at java.base/java.util.TimeZone.toZoneId0(TimeZone.java:594)
	at java.base/java.util.TimeZone.toZoneId(TimeZone.java:582)
	at java.base/java.time.ZoneId.systemDefault(ZoneId.java:275)
	at java.base/java.time.Clock.systemDefaultZone(Clock.java:185)
	at fr.brouillard.oss.cssfx@11.5.1/fr.brouillard.oss.cssfx.impl.log.CSSFXLogger.<clinit>(CSSFXLogger.java:35)
	at fr.brouillard.oss.cssfx@11.5.1/fr.brouillard.oss.cssfx.CSSFX$CSSFXConfig.start(CSSFX.java:207)
	at fr.brouillard.oss.cssfx@11.5.1/fr.brouillard.oss.cssfx.CSSFX.start(CSSFX.java:56)
	at spoty.core@230.46.17/inc.nomard.spoty.core.views.splash.SplashScreenController.lambda$startApp$1(SplashScreenController.java:285)
	at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@21.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@21.0.2/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.mnode.ical4j.core@4.0.0-beta2/net.fortuna.ical4j.model.DefaultZoneRulesProvider.<clinit>(DefaultZoneRulesProvider.java:23)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 24 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 34 more`

**Comment by dlemmermann** [comment]
I updated the ical4j dependency and released version 11.12.7. Please try with that one. It no longer has a dependency to jooq/jool ...

**Comment by infinite-dev22** [comment]
Thanks so much @dlemmermann, I am grateful. I had found a work around just afew moments back. I exclude `jool` and add `slf4j`. I tried adding ical4j but this didn't work.
`
    implementation 'org.slf4j:slf4j-api:2.1.0-alpha1'
    implementation('com.calendarfx:view:11.12.6') {
        exclude group: 'org.jooq'
    }`
Let me update my dependency. Thanks again
